FROM python:3.10-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y \
    g++ \
    unixodbc-dev \
    gnupg \
    curl \
    apt-transport-https \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Add Microsoft's GPG key
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Add Microsoft's SQL Server Debian repository
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Install SQL Server drivers and SQL Server Command Line tools
RUN apt-get update \
    && ACCEPT_EULA=Y apt-get -y install msodbcsql17 mssql-tools \
    && rm -rf /var/lib/apt/lists/*

# Copy only necessary scripts into the container
COPY ./scripts/entrypoint-db-init.sh /app/entrypoint-db-init.sh
COPY database_scripts /app/sql_scripts

# Add and set permissions for docker-compose-wait
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.12.0/wait /wait
RUN chmod +x /wait

# Set permissions for docker-entrypoint-db.sh
RUN chmod +x /app/entrypoint-db-init.sh

# Copy data ingestion process
COPY ./ontario_schools.py ./ontario_schools.py
COPY ./ontario_schools ./ontario_schools
COPY ./requirements.txt ./requirements.txt
COPY ./data_cache ./data_cache

RUN pip install -r requirements.txt

# Run the command on container startup
ENTRYPOINT ["./entrypoint-db-init.sh"]